// LOCALHOST
###
GET http://localhost:3000/
###
GET http://localhost:3000/contacts/contactId
###
GET http://localhost:3000/contacts/contactId
###
GET http://localhost:3000/contacts/contactId
###
GET http://localhost:3000/contacts

### create new contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"User", "lastName":"Tester", "email":"user@test.com", "favoriteColor":"Yellow", "birthday":"1958-08-28"
}

### update contact with specified id
PUT http://localhost:3000/contacts/contactId HTTP/1.1
content-type: application/json

{
    "favoriteColor":"Blue"
}
###
PUT http://localhost:3000/contacts/contactId HTTP/1.1
content-type: application/json

{
    "email":"fake@email.com", "favoriteColor":"Green"
}

### delete contact with specified id
DELETE  http://localhost:3000/contacts/contactId HTTP/1.1

// RENDER
###
GET https://mendozahectorcse341.onrender.com
###
GET https://mendozahectorcse341.onrender.com/contacts/contactId
###
GET https://mendozahectorcse341.onrender.com/contacts/contactId
###
GET https://mendozahectorcse341.onrender.com/contacts/contactId
###
GET https://mendozahectorcse341.onrender.com/contacts

### create new contact
POST https://mendozahectorcse341.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"User", "lastName":"Tester", "email":"user@test.com", "favoriteColor":"Yellow", "birthday":"1958-08-28"
}

### update contact with specified id
PUT https://mendozahectorcse341.onrender.com/contacts/contactId HTTP/1.1
content-type: application/json

{
    "favoriteColor":"Blue"
}
###
PUT https://mendozahectorcse341.onrender.com/contacts/contactId HTTP/1.1
content-type: application/json

{
    "email":"fake@email.com", "favoriteColor":"Green"
}

### delete contact with specified id
DELETE  https://mendozahectorcse341.onrender.com/contacts/contactId HTTP/1.1