// LOCALHOST
###
GET http://localhost:3000/
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/636984abcc71d4d728e33eb7
###
GET http://localhost:3000/contacts/636984abcc71d4d728e33eb8
###
GET http://localhost:3000/contacts/636984abcc71d4d728e33eb9

### create new contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"User", "lastName":"Tester", "email":"user@test.com", "favoriteColor":"Yellow", "birthday":"1958-08-28"
}

### update contact with specified id
PUT http://localhost:3000/contacts/636c54af5cb54f6434083f51 HTTP/1.1
content-type: application/json

{
    "favoriteColor":"Blue"
}
###
PUT http://localhost:3000/contacts/636c54af5cb54f6434083f51 HTTP/1.1
content-type: application/json

{
    "email":"fake@email.com", "favoriteColor":"Green"
}

### delete contact with specified id
DELETE  http://localhost:3000/contacts/636c54af5cb54f6434083f51 HTTP/1.1

// RENDER
###
GET https://mendozahectorcse341.onrender.com
###
GET https://mendozahectorcse341.onrender.com/contacts
###
GET https://mendozahectorcse341.onrender.com/contacts/
###
GET https://mendozahectorcse341.onrender.com/contacts/
###
GET https://mendozahectorcse341.onrender.com/contacts/

### create new contact
POST https://mendozahectorcse341.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"User", "lastName":"Tester", "email":"user@test.com", "favoriteColor":"Yellow", "birthday":"1958-08-28"
}

### update contact with specified id
PUT https://mendozahectorcse341.onrender.com/ HTTP/1.1
content-type: application/json

{
    "favoriteColor":"Blue"
}
###
PUT https://mendozahectorcse341.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
    "email":"fake@email.com", "favoriteColor":"Green"
}

### delete contact with specified id
DELETE  https://mendozahectorcse341.onrender.com/contacts/ HTTP/1.1